spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    open-in-view: false
app:
  image:
    bucket: /Users/murzabekmackbook/IdeaProjects/mentorDmdev/first-maven-project/images